version: "3"

services:
  web:
    image: golang:1.20.8
    env_file: docker_env_file
    command: go run ./web
    volumes:
      - .:/src/go/dousheng
    working_dir: /src/go/dousheng
    ports:
      - "8080:8000"
    links:
      - user
      - feed
      - relation
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD

  user:
    image: golang:1.20.8
    env_file: docker_env_file
    command: go run ./service/user
    volumes:
      - .:/src/go/dousheng
    working_dir: /src/go/dousheng
    expose:
      - "9001"
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD

  feed:
    image: golang:1.20.8
    env_file: docker_env_file
    command: go run ./service/feed
    volumes:
      - .:/src/go/dousheng
    working_dir: /src/go/dousheng
    expose:
      - "9002"
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD

  relation:
    image: golang:1.20.8
    env_file: docker_env_file
    command: go run ./service/relation
    volumes:
      - .:/src/go/dousheng
    working_dir: /src/go/dousheng
    expose:
      - "9003"
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD

secrets:
  MYSQL_USER:
    file: "MYSQL_USER.env"
  MYSQL_PASSWORD:
    file: "MYSQL_PASSWORD.env"
