// Code generated by hertz generator.

package feed

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your status...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your status...
	return nil
}

func _feedMw() []app.HandlerFunc {
	// your status...
	return nil
}

func _feed0Mw() []app.HandlerFunc {
	// your status...
	return nil
}
