// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"simple-douyin-backend/web/biz/router/feed"
	relation "simple-douyin-backend/web/biz/router/relation"
	"simple-douyin-backend/web/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	relation.Register(r)

	feed.Register(r)

	user.Register(r)
}
